### ISSUE TITLE
Having trouble displaying the posts on my theme.

### ISSUE THREAD

**Issue by RyanTG** [dancwilliams/wordpress_to_staticman_comments#1]
I know you haven't had to deal with this for a while, but I could use some help.

I modified this script to work with my domain, and it worked, but now I'm failing to actually display my imported comments. I think it must have something to do with my folder paths. Can you tell me if anything stands out here?

My blog repo is private right now, as I get it settled, but here are some snippets.

in staticman.yml

````
  path: "data/comments/{options.entryId}"
````

But I'm not 100% sure what the entryID is. I have also tried `options.slug`.

My folder structure looks like:
`data/comments/who-lambada-better` with "who-lambada-better" being the url of the post. When I leave a new comment on my live site, the folder is something like `b900240fbd017bf84f2675cabc44a1d1`. I'm guessing that is the entryID?

So, clearly my theme is looking for something other than a nice slug. Here is my [theme's code for this](https://github.com/pacollins/hugo-future-imperfect-slim/blob/bdf95347c33f19aabca7ed1d978291b1fb1e7a73/layouts/_default/staticman.html).

I'm just not sure how to have it use the clean slug instead of the unique entryid. Maybe I should check with the theme folks.

**Comment by RyanTG** [comment]
I resolved this by using `options.slug` and in the html:

````
{{- $postSlug := .File.BaseFileName -}}
<input type="hidden" name="options[slug]" value="{{ $postSlug }}">
````

Closing! Sorry about that 12:30am issue.

**Comment by dancwilliams** [comment]
@RyanTG Glad you got it working! Long morning in the office so I was slow to respond. Never a problem to ask questions. Glad to see someone got use out of this.
